[package]
name = "venv_lib"
version = "0.2.3"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/dev-venv/rust-lib"
description = "A small toolkit"
rust-version = "1.68"
keywords = ["lib", "utils"]

[dependencies]
rand = "0.8.5"
chrono = "0.4.24"
serde_json = "1.0.95"
uuid = { version = "1.3.1", features = ["v4"] }
reqwest = { version = "0.11.16", features = ["blocking"] }
