[package]
name = "venv_lib"
version = "0.2.6"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/dev-venv/rust-lib"
description = "A small toolkit"
rust-version = "1.68"
keywords = ["lib", "utils"]

[dependencies]
rand = "0.8.5"
chrono = "0.4.30"
serde_json = "1.0.105"
uuid = { version = "1.4.1", features = ["v4"] }
reqwest = { version = "0.11.20", features = ["blocking"] }

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3.9"
default-features = false
features = ["consoleapi", "processenv", "winbase"]
