[package]
name = "ufa"
version = "1.0.5"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/alan-venv/ufa-rs"
description = "A small toolkit"
rust-version = "1.72"
keywords = ["lib", "utils"]

[dependencies]
rand = "0.8.5"
chrono = "0.4.31"
serde_json = "1.0.107"
uuid = { version = "1.4.1", features = ["v4"] }
reqwest = { version = "0.11.22", features = ["blocking"] }
base64 = "0.21.5"

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3.9"
default-features = false
features = ["consoleapi", "processenv", "winbase"]
