on:
  push:
    paths-ignore:
      - "README.md"
      - ".github/*"
    branches: "main"

env:
  CRATES_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

jobs:
  publish:
    name: Publish to crate.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: stable
      - name: Build package
        run: cargo build --release
      - name: Publish package
        run: cargo publish --token ${CRATES_TOKEN}
