name: Rust

on:
  push:
    paths-ignore:
    - 'README.md'
    - '.github/'
    branches: "main"

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Build package
        run: cargo build --release
      - name: Publish package
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: cargo publish --token $CRATES_IO_TOKEN
